### ISSUE TITLE
When a new user is created the progress bar for the album runs infinately without stop

### ISSUE THREAD

**Issue by AthulKrishna14310** [AthulKrishna14310/inlens_official#60]
![Screenshot_20200411-115224_InLens](https://user-images.githubusercontent.com/37478917/79036981-0d5dbf00-7beb-11ea-8ee9-6b0499ff142a.jpg)

**Comment by elsonjose** [comment]
i think this issue is already fixed

**Comment by AthulKrishna14310** [comment]
Its not done yet . You have to delete your account from InLens Authentication , Clear your app data and try installing the app . Then please check
