### ISSUE TITLE
Scanned album is appearing *first* while sorting users Cloud-Albums

### ISSUE THREAD

**Issue by AthulKrishna14310** [AthulKrishna14310/inlens_official#62]

**Comment by elsonjose** [comment]
The scanned album is the current active album. Therefore shouldn't it appear first ?

**Comment by AthulKrishna14310** [comment]
No that , If we scan or invite Cloud-Album then Quit from it , after that if we created another cloud album that rearrangment went wrong. 
That is the scanned album even if that is expired is seen first and the active album is seen after that
