### ISSUE TITLE
 Participants recycler view should refresh , 

### ISSUE THREAD

**Issue by AthulKrishna14310** [AthulKrishna14310/inlens_official#87]
After the added photographers other than the admin exit the album participation the add member + button should be invisible . This recycler view is not refreshing now if a scanned or linked participants exits the album.
![Screenshot_20200524-005338_WhatsAppBusiness](https://user-images.githubusercontent.com/37478917/82738999-cc180d80-9d59-11ea-9565-bf959eb5657f.jpg)

**Comment by elsonjose** [comment]
some more description is needed
