### ISSUE TITLE
Notification text

### ISSUE THREAD

**Issue by AthulKrishna14310** [AthulKrishna14310/inlens_official#92]
![Screenshot_20200524-005413_WhatsAppBusiness](https://user-images.githubusercontent.com/37478917/82739241-b1df2f00-9d5b-11ea-9a57-6a7030acc3e5.jpg)

**Comment by elsonjose** [comment]
i do not have this issue.

**Comment by elsonjose** [comment]
Saw this problem via joining invite link

**Comment by elsonjose** [comment]
Active Album should be first in the list
